version: 0.0
Resources:
  - TargetService:
      Type: AWS::Lambda::Function
      Properties:
        Name: "wgt-guru-pink-getAllSwings"
        Alias: "staging"  # Use the alias of the staging deployment

  - TargetService:
      Type: AWS::Lambda::Function
      Properties:
        Name: "wgt-guru-pink-createSwing"
        Alias: "staging"  # Use the alias of the staging deployment

  - TargetService:
      Type: AWS::Lambda::Function
      Properties:
        Name: "wgt-guru-pink-healthcheck"
        Alias: "staging"  # Use the alias of the staging deployment

Hooks:
  BeforeAllowTraffic:
    - Location: "smokeTest.sh"  # Path to your smoke test script
      Timeout: 600  # Maximum time allowed for the smoke test
