version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g serverless   # Install serverless framework globally
      - npm ci                      # Install project dependencies

  pre_build:
    commands:
#      - export LIVE_TRAFFIC_STAGE=$(aws lambda get-function-configuration --function-name live-traffic-lambda --query 'Environment.Variables.STAGE' --output text)
#      - echo "Live Traffic Stage: $LIVE_TRAFFIC_STAGE"

  build:
    commands:
      - serverless deploy --stage non-traffic --config serverless.ts

artifacts:
  files:
    - template.yaml
    - packaged.yaml
    - serverless.ts
