version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running all the unit tests...
      - npm run test

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code...
      - npm run build

  post_build:
    commands:
      - echo executing canary deployment
      - npx serverless deploy
#      - aws stepfunctions start-execution --state-machine-arn arn:aws:states:us-east-1:577152972443:stateMachine:Canary-Lane --input '{"stackName":"wgt-guru-dev"}'

#
#artifacts:
#  files:
#    - ".serverless/cloudformation-template-update-stack.json"
#    - ".serverless/serverless-state.json"
#  base-directory: "./"
