config:
  target: 'https://061aqiq135.execute-api.us-east-1.amazonaws.com/dev'
  processor: './processor.js' # Path to the custom processor file
  phases:
    - duration: 20
      arrivalRate: 5

scenarios:
  - flow:
      - get:
          url: '/healthcheck'
          beforeRequest:
            - 'addErrorFlag' # Call the custom function before each request