version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - sls deploy -v --stage $STAGE
  post_build:
    commands:
      - echo 'Extracting Lambda ARN from the stack'
      - |
        LAMBDA_ARN=$(aws cloudformation describe-stack-resource --stack-name $STACK_NAME --logical-resource-id $FUNCTION_NAME --query 'StackResourceDetail.PhysicalResourceId' --output text)
        echo "Lambda ARN: $LAMBDA_ARN"
      - echo 'Preparing deployment artifacts...'
      - |
        if [ "$DEPLOYMENT_TRIGGER" = "true" ]
        then
          aws s3 cp ./package s3://trigger-deployment-bucket/package --recursive
        else
          aws s3 cp ./package s3://non-trigger-deployment-bucket/package --recursive
        fi
