# /my-service/stacks/codebuild/serverless.yml
service: my-service-codebuild

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket: 
    name: ${self:custom.bucket}
    serverSideEncryption: AES256
  deploymentPrefix: codebuild
  stackName: ${self:service}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - codebuild:StartBuild
      Resource: "*"

custom:
  bucket: ${env:BUCKET_NAME}

resources:
  Resources:
    MyCodeBuildProject:
      Type: 'AWS::CodeBuild::Project'
      Properties:
        Artifacts:
          Type: NO_ARTIFACTS
        Environment:
          ComputeType: BUILD_GENERAL1_SMALL
          Image: 'aws/codebuild/standard:4.0'
          Type: LINUX_CONTAINER
        ServiceRole: <CodeBuildServiceRoleArn>
        Source:
          Type: GITHUB
          Location: <GitHubRepoUrl>
          GitCloneDepth: 1
        Triggers:
          Webhook: true
          FilterGroups:
            - - Type: EVENT
                Pattern: PUSH,PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
              - Type: HEAD_REF
                Pattern: ^refs/heads/main$

plugins:
  - serverless-prune-plugin
